version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: time1spacex/foodgram_backend
    env_file: backend/.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/foodgram_backend/media/
  frontend:
    env_file: backend/.env
    image: time1spacex/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: time1spacex/foodgram_nginx
    env_file: backend/.env
    depends_on:
      - backend
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/app/foodgram_backend/media/
      - ./docs/:/usr/share/nginx/html/api/docs/